name: tdd-git-app
version: "1.0"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    env_file:
      - ./.env
    depends_on:
      - database
    networks:
      - app

  database:
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app
  
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 8080:8080
    environment:
      PGADMIN_DEFAULT_EMAIL: p@p.com 
      PGADMIN_DEFAULT_PASSWORD: 123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      PGADMIN_LISTEN_PORT: 8080
    networks:
      - app

networks:
  app:
    driver: bridge